#WE need a version
version: '3'
#services
services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "8081:3000"
    volumes:
      - /app/node_modules
      - .:/app
